### ISSUE TITLE
Fatal exception: concurrent modification exception 

### ISSUE THREAD

**Issue by hbj508** [gotev/android-cookie-store#37]
`
java.util.ArrayList$Itr.next (ArrayList.java:860)
net.gotev.cookiestore.SharedPreferencesCookieStore.add (SharedPreferencesCookieStore.kt:107)
java.net.CookieManager.put (CookieManager.java:360)
net.gotev.cookiestore.WebKitSyncCookieManager.put (WebKitSyncCookieManager.kt:37)
`

**Comment by gotev** [comment]
could you please give more context and steps to reproduce?

**Comment by hbj508** [comment]
Happens in prod after upgrade to okhttp5.0-alpha10. not able to reproduce locally

**Comment by gotev** [comment]
please keep using latest okhttp 4.x. OkHttp 5 is not supported yet.

**Comment by hbj508** [comment]
Any plans to support it? We had to use fastfallback feature which is available in okhttp 5.0

**Comment by gotev** [comment]
you're welcome to contribute with a PR

**Comment by hbj508** [comment]
Hey this happens in older okhttp versions as well. Can you please provide a fix for concurrent modification exception

**Comment by gotev** [comment]
What version are you using? Never experienced this personally, so as I asked initially, more context and steps to reproduce are needed to debug this, which needs to be replicated first. A test would be awesome and you're welcome to open a PR. As a quick check, ensure your code is not reading and accessing cookies from more than one thread and if so, consider synchronizing access. From what I see, the exception gets thrown from java.net.CookieManager which is JVM standard library.

**Comment by hbj508** [comment]
We are using 4.9.1. 
We are not able to reproduce it locally. Was thinking will it help if we switch to concurrent hashmap like below? 
```
 internal val uriIndex = ConcurrentHashMap<URI, MutableList<HttpCookie>>()

```

**Comment by hbj508** [comment]
Hey @gotev can we replace linkedhasmap to concurrentHashmap? It seems be thread safe

**Comment by gotev** [comment]
So, are you using 4.9.1 with cookie store 1.5.0?

From what I see, that snippet you posted is from the InMemoryCookieStore, but the posted stack trace at the beginning of the thread is not referring to it, but to java.net.CookieManager so I'm not getting the correlation between the two without further evidence, given also that InMemoryCookieStore has locked reads and writes.

**Comment by vicky7230** [comment]
I am facing a simialr issue: 

```
Fatal Exception: java.util.ConcurrentModificationException:    
       at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)    
       at java.util.ArrayList$Itr.next(ArrayList.java:1064)    
       at uΨجЮףλ.tחΡНΖج.sмץלбН.SharedPreferencesCookieStore.add(:56)    
       at java.net.CookieManager.put(CookieManager.java:357)    
       at uΨجЮףλ.tחΡНΖج.sмץלбН.WebKitSyncCookieManager.put(:5)    
       at net.gotev.cookiestore.okhttp.JavaNetCookieJar.saveFromResponse(:75)    
       at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.kt:207)    
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:85)    
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)    
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)    
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)    
       at com.mttnow.android.gbt.core.network.interceptor.InvalidAppInterceptor.intercept(InvalidAppInterceptor.kt:33)    
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)    
       at com.mttnow.android.gbt.core.network.interceptor.GbtHeaderInterceptor.intercept(GbtHeaderInterceptor.kt:109)    
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)    
       at com.mttnow.android.gbt.core.network.interceptor.LoggerInterceptor.intercept(LoggerInterceptor.kt:16)    
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)    
       at com.mttnow.android.gbt.core.network.interceptor.NetworkConnectionInterceptor.intercept(NetworkConnectionInterceptor.kt:19)    
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)    
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:154)    
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)    
       at com.mttnow.android.gbt.core.network.interceptor.GbtApiVersionInterceptor.intercept(GbtApiVersionInterceptor.kt:45)    
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)    
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)    
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)    
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)    
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)    
       at java.lang.Thread.run(Thread.java:1119)
```

Have raised a pr for the same: https://github.com/gotev/android-cookie-store/pull/41
